### GENERAL SETTINGS
feature_list: data/miRNA_list.csv
mapping_info_rna_classes: data/mapping_infos/overall_composition.detailed_mod.mapped_perc_CA1_CA2.csv
mapping_info_rna_classes_microglia: data/mapping_infos/overall_composition.detailed_mod.mapped_perc_microglia.csv

results_folder: results/results_rpmm

#--------------------- modules --------------------
# additionnal modules: diff_exp_values_table, mirna_expression_median_violin_plot, pathway_analysis_results_heatmap_plots, halushka_violin_plots, make_publication_folder

# make publication folder
# modules: [
#     make_publication_folder,
# ]

#microglia
modules: [ 
  mapping_stats_bar_plot,
] 

# create publication folder
# modules: [ 
#     make_publication_folder
# ]

#---------- common parameter and colours ----------
common:
  input:
    raw_data_folder: raw_data/data
    annotation_data_folder: data/annotations
    data_sub_set: microglia
    rna_class: "ncRNA"
    rna_classes: ["piRNA", "lncRNA", "miRNA", "snoRNA", "snRNA", "tRNA", "rRNA", "scaRNA"] #, "circRNA"
    feature_filtering: filtered
    norm: rpmm_norm
    detection_group: age
    detection_rate: 10p
    identifier_column: SampleID
  parameters:
    set_seed: 42
  plots:
    dpi: 600
    font_family: "Arial"
    image_height: 6
    image_width: 9
    image_units: cm
    font_size: 9
    font_size_header: 12

colors:
  - direction:
      up: "#E09900"
      up_light: "#E9BD5B"
      light: "#F4F5F5"
      down_light: "#91C2AB"
      down: "#488468"
      pos: "#E09900"
      neg: "#488468"
      enriched: "#E09900"
      depleted: "#488468"
  - brain_region:
      cc: "#1c93d1" 
      cer: "#e41e27"
      cor: "#15a750"  
      cp: "#7962a4" 
      ent: "#f2932d"
      hi: "#fad326"  
      hi2: "#231f1f" 
      hy: "#70c2eb" 
      med: "#f1aaa6"
      #mid: "#063804"
      olf: "#c6bbd5" 
      plx: "#f6c589" 
      pon: "#b3b8c0" 
      svz: "#ede29d"   
      th: "#b65376" 
      vis: "#ef98c1"  
  - brain_region_text:
      cc: "#ffffff" 
      cer: "#ffffff" 
      cor: "#ffffff" 
      cp: "#ffffff" 
      ent: "#000000" 
      hi: "#000000" 
      hi2: "#ffffff" 
      hy: "#000000" 
      med: "#000000"
      #mid: "#000000"
      olf: "#000000" 
      plx: "#000000" 
      pon: "#000000"  
      svz: "#000000"    
      th: "#ffffff" 
      vis: "#000000" 
  #- cohort:
  #    CA1: "#24580E"
  #    CA2: "#8b2222"
  - sex:
      Male: "#4dc8bf"
      Female: "#7b5aa6"
      #nan: "#000000"
  - age:
      #3: "#dd3226"
      #12: "#faae61"
      #15: "#fce091"
      #18: "#e1f3fa"
      ##19: "#e1f3fa"
      #21: "#acdbec"
      #26: "#4576b6"
      #28: "#323995"
      ##nan: "#000000"
      3: "#C74132"
      12: "#EFB16E"
      15: "#F7E19B"
      18: "#E4F2F9"
      21: "#B5DAEA"
      26: "#5175B1"
      28: "#333990"
  - plate:
      P23: "#238200"
      P24: "#5A9100"
      P25: "#919F00"
      P26: "#C8AD00"
      P27: "#FFBB00"
      P28: "#FE8C16"
      P29: "#FC5C2C"
      P30: "#CC4670"
      P31: "#9C2FB3"
      P32: "#755DC6"
      P33: "#4E8AD9"
      P34: "#27B8EC"
      P35: "#00E5FF"
  - rna_classes: 
      miRNA: "#98c27c"
      snoRNA: "#6baf6b"
      piRNA: "#9f4e07"
      rRNA: "#01592f"
      tRNA: "#1f743a"
      snRNA: "#399852"
      scaRNA: "#003c24"
      lincRNA: "#FDB863"
      lncRNA: "#e1a458"
      others: "#7F7F7F"
      mRNA: "#c37012"
      circRNA: "#002918"
  - clusters:
      I: ["#CC6827"]
      II: ["#25578E"]
      III: ["#A5261C"]
      IV: ["#3A7E27"]
      V: ["#6D4B98"]

colors_microglia:
  - direction:
      up: "#E09900"
      up_light: "#E9BD5B"
      light: "#F4F5F5"
      down_light: "#91C2AB"
      down: "#488468"
      pos: "#E09900"
      neg: "#488468"
      enriched: "#E09900"
      depleted: "#488468"
  - age:
      young: "#C74132"
      old: "#B5DAEA"
  - age_text:
      young: "#ffffff" 
      old: "#000000" 
  - rna_classes: 
      miRNA: "#98c27c"
      snoRNA: "#6baf6b"
      piRNA: "#9f4e07"
      rRNA: "#01592f"
      tRNA: "#1f743a"
      snRNA: "#399852"
      scaRNA: "#003c24"
      lincRNA: "#FDB863"
      lncRNA: "#e1a458"
      others: "#7F7F7F"
      mRNA: "#c37012"
      circRNA: "#002918"

xticks_names:
  - categories:
      brain_region_capital: "Brain region"
      brain_region: "brain region"
      age_capital: "Age (month)"
      age: "age (month)"
      sex_capital: "Sex"
      sex: "sex"
      mouse_ID_capital: "Individual"
      mouse_ID: "individual"
  - age:
      3: "3m"
      12: "12m"
      15: "15m"
      18: "18m"
      21: "21m"
      26: "26m"
      28: "28m"
  - brain_region:
      cc: "cc"
      cer: "cer"
      cor: "cor"
      cp: "cp"
      ent: "ent"
      hi: "hi ant."
      hi2: "hi post."
      hy: "hy"
      med: "med"
      olf: "olf"
      plx: "plx"
      pon: "pon"
      svz: "svz"
      th: "th"
      vis: "vis"

xticks_names_microglia:
  - categories:
      age_capital: "Age (month)"
      age: "age (month)"
      mouse_ID_capital: "Individual"
      mouse_ID: "individual"
  - age:
      young: "young"
      old: "old"

#------------------ plots and tables ------------------
mapping_stats_bar_plot:
  grouping: 
    - g1: ["age", "sample"]
    - g2: ["age"]
  image_size:
    - image_height: 6
    - image_width: 6


expressed_features_per_rna_class_bar_plot:
  grouping: brain_region
  min_detect_raw: 5
  detection_rate: 10
  image_size:
    image_height: 6
    image_width: 6

expressed_features_per_rna_class_line_plot:
  parameters:
    grouping: [brain_region, age]
    min_detect_raw: 5
    detection_rate: 10
    curve: 
        - c1: ["poly", 2]
        - c2: ["poly", 3]
        - c3: ["loess"]
    plot_layout:
        plot_nrows: 3
        plot_ncols: 5
    plot_size: 
        image_height: 9
        image_width: 15
  manual_plots_parameters:
    tissues: [cc, cer, cor, cp, ent, hi, hi2, hy, med, olf, plx, pon, svz, th, vis] #[cer, cor, hi, olf] cc: "#1c93d1" 
    plot_layout:
        plot_nrows: 4
        plot_ncols: 4
    plot_size: 
        image_height: 12
        image_width: 12

# metadata_overview_tables:
#   combinations:
#     - SampleID:
#         g: ["brain_region", "age"]
#         pooling: []
#     - SampleID:
#         g: ["brain_region", "sex"]
#         pooling: []
#     - SampleID:
#         g: ["age", "sex"]
#         pooling: []
#     - mouse_ID:
#         g: ["age", "brain_region"]
#         pooling: []
#     - mouse_ID:
#         g: ["age", "brain_region"]
#         pooling: ["young", "young", "young", "adult", "adult", "old", "old"] #pooling only possible if parameter sortable (age, time, timepoint)

umap:
  top_list: ["all"]
  neighbors: [5,10,25] # [5 -> 50]
  min_dist: [0.1,0.25] # [0.01 -> 0.5]
  metric: [euclidean,correlation]
  init: [random] # [random,spectral]
  seed: [42]
  norm: [raw,std]
  properties: 
    - p1: [brain_region] # colour
    - p2: [age]
    - p3: [sex]
    - p4: [brain_region, age] # colour, shape
    - p5: [brain_region, sex]

correlation_comp_age_per_rna_class_ridgeline_plot:
  props: ["brain_region", "age"]
  method: [pearson,spearman]
  corr_th: [0.5]
  adjustment: BH
  adj_p_value: 0.05
  plot_size: 
    image_height: 6
    image_width: 9
