### GENERAL SETTINGS
mapping_info: data/mapping_infos/mapping_vs_mm10_mis1_microglia.csv  #../../data_microglia/mapping_infos/mapping_vs_mm10_mis1.csv

results_folder: preprocessing

#--------------------- modules --------------------

# _CA1
modules: [ 
  preprocessing,
] 

#---------- common parameter and colours ----------
common:
  input:
    preprocesing_data_folder: raw_data/data
    annotation_data_folder: data/annotations
    data_sub_set: microglia
    rna_class_list: ["miRNA"]      
    norm: ["rpmm_norm"]
  parameters:
    set_seed: 42


#----------------- preprocessing -----------------
preprocessing:
  log_list: [2, 10]
  min_detection_list: [5]
  number_of_reads: 0
  detection_rate_list: [0.1]
  filter_variable: age
  id_col: SampleID
  fastq_filename_col: fastq_name

